name: CD/CD-client

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: 'Create env file'
        run: |
          touch .env
          echo NEXT_PUBLIC_API_DOMAIN="${{ secrets.NEXT_PUBLIC_API_DOMAIN }}" >> .env
      #     cat .env
      - name: build image
        run: docker build -t upalmofficial/u-palm-client .
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: push image to docker hub
        run: docker push upalmofficial/u-palm-client
      - name: GitHub Action for DigitalOcean - doctl
        uses: digitalocean/action-doctl@v2.5.1
        with:
          token: ${{secrets.DIGITALOCEAN_TOKEN}}
      - name: rollout client deployment
        run: doctl kubernetes cluster kubeconfig save 691b6726-f89e-4a4b-b594-eb1cfe0fb938 && kubectl rollout restart deployment client-u-palm-deployment
    
